name: Workflow-1
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment we are going to deploy in'
        type: environment
        required: true
      Name:
        description: input the name
        required: true
        default: dennis
  schedule:
          - cron: '*/15 6 6 * *'
          
jobs:

  echo-step:
    runs-on: ubuntu-latest
    steps:
      - run :  echo "hello ${{inputs.Name}}"
          
